### PR TITLE
[DO NOT MERGE] Move cursor to newly created window

### LINKED ISSUE #9: Move cursor to newly opened window that has focus
Can you make it so the cursor moves to newly opened window that is focused?

If the newly opened window is not focused (and a "XXX is ready" notification should appear) then don't move cursor.

### PR DESCRIPTION
**Pull request by ghost**
Fixes https://github.com/buzztaiki/gnome-shell-extension-alt-tab-move-mouse/issues/9

### CODE REVIEW

**Comment by ghost** [comment]
The ` if ( !window.demands_attention )`, I don't know what to do about it as it's probably unsafe.

Tried `appears_focused()` as per [this](https://gjs-docs.gnome.org/meta11~11_api/meta.window#method-appears_focused) but it's completely useless, it never returns `true`

**Comment by buzztaiki** [comment]
Thank you for your contributing. This is so awesome.
 I am not that familiar with Meta and Clutter either ;)

> The if ( !window.demands_attention ), I don't know what to do about it as it's probably unsafe.

why do you think it is not unsafe?

I will test this branch and think better solution in this weekend.

**Comment by ghost** [comment]
> Thank you for your contributing. This is so awesome. I am not that familiar with Meta and Clutter either ;)
> 
> > The if ( !window.demands_attention ), I don't know what to do about it as it's probably unsafe.
> 
> why do you think it is not unsafe?
> 
> I will test this branch and think better solution in this weekend.

The Goal: I want cursor to move only when newly created window is in focus.

- `appears_focused()` or `has_focus()` should had been the way to go, but none of them work at all (both always returns `false`).

- In theory, `demands_attention` is only `true` when it's not in focus (opened in background or in other workspace), but then based on my experiments this is not the case. In fact `demands_attention` appears to always return `false` as well.

**Comment by ghost** [comment]
I'm not familiar with gnome development so all i could do was trial and error. maybe there's a better way to get `appears_focused()` in realtime.
if any i'll just go for sleep now since it's too late in my timezone.

**Comment by ghost** [comment]
@buzztaiki 

With all the pieces glued now it should work™:

1. A newly created window won't have focus by default, this is GNOME's design
	- This explains why `appear_focused` never returns `true`. because at the time window was created it won't have focus
2. Keep track of multiple signals of newly created window
	- If WM decides that new window has focus, then try moving cursor and destroy the object
	- if WM decides that new window has no focus, a "X is ready" notification appears and should trigger either `demands-attention` or `urgent`, which then destroy the object
	- I'm not sure about `unmanaged` but kept it since it's in [windowAttentionHandler.js](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/js/ui/windowAttentionHandler.js#L69)

What's working:

- new window will have cursor centered automatically
- if new window is opened in background, cursor won't move
- enabling / disabling extension works


Problems:

1. `this._destroy()` can't be used by `this._window.connectObject` directly. for example:

```
this._window.connectObject(
  'notify::demands-attention', this._destroy(),
  'notify::urgent', this._destroy(),
  'focus', () => this._focus(),
  'unmanaged', () => this._destroy(), 
  this);
```

This breaks cursor movement in too many ways. I don't know why nor how to fix it. `this._destroy.bind()` or  `this._destroy.bind(this)`  won't work either.

2. error thrown when switching workspace

```
JS ERROR: TypeError: this._window is undefined
```

I don't know why or how to fix it.

**Comment by ghost** [comment]
Also `WindowType` might need to be taken into consideration. currently I use `window.allows_move()` to filter most of things we don't want, but then under wayland sometimes cursor still randomly jumps to top left corner. a better approach would be allowing only

- `NORMAL = 0`
- `DIALOG = 3`
- `MODAL_DIALOG = 4`

as per the documentation:

https://gjs-docs.gnome.org/meta11~11_api/meta.windowtype

but then i'm too tired currently so i'll leave it as is for now.

**Comment by ghost** [comment]
now looking back i feel like my code is too dumb. anyway the work is being continued here:
https://github.com/LeonMatthes/mousefollowsfocus/pull/6/files

**Pull request closed without merging**
